name: Teste do projeto

on:
  push:
    branches: [tests]
  pull_request:
    branches: [tests]

jobs:
  test-client-app:
    runs-on: ubuntu-latest

    # Configurar PostgreSQL como serviço
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: api
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: db
          POSTGRES_INITDB_ARGS: "-c client_encoding=UTF8"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Mask DB_PASSWORD
        run: |
          echo "::add-mask::DB_PASSWORD=${{ secrets.DB_PASSWORD }}"

      - name: Criar .env file
        working-directory: .
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=api" >> .env
          echo "DB_NAME=db" >> .env

      - name: Preparando ambiente
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aguardar PostgreSQL estar disponível
        run: |
          for i in {1..30}; do
            sudo -u postgres psql -c "SELECT 1 FROM pg_user WHERE usename = 'api'" && break
            echo "Waiting for POSTGRESQL..."
            sleep 2
          done

      - name: Executando migrate
        run: python manage.py migrate

      - name: Executando testes
        working-directory: ./clientes
        run: |
          pytest -v

      - name: Avaliando Complexidade de Código
        working-directory: ./clientes
        run: |
          radon cc -a .
      - name: Avaliando Qualidade de Código no models
        working-directory: ./
        run: |
          pylint ./clientes/models.py

      - name: Avaliando Qualidade de Código no serializers
        working-directory: ./
        run: |
          pylint ./clientes/serializers.py

      - name: Avaliando Qualidade de Código no views
        working-directory: ./
        run: |
          pylint ./clientes/views.py
